export default {
  login: 'akashdubey2211',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/akashdubey2211',
  html_url: 'https://github.com/akashdubey2211',
  followers_url: 'https://api.github.com/users/akashdubey2211/followers',
  following_url:
    'https://api.github.com/users/akashdubey2211/following{/other_user}',
  gists_url: 'https://api.github.com/users/akashdubey2211/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/akashdubey2211/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/akashdubey2211/subscriptions',
  organizations_url: 'https://api.github.com/users/akashdubey2211/orgs',
  repos_url: 'https://api.github.com/users/akashdubey2211/repos',
  events_url: 'https://api.github.com/users/akashdubey2211/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/akashdubey2211/received_events',
  type: 'User',
  site_admin: false,
  name: 'akashdubey2211',
  company: 'MERN Stack developer',
  personal: 'https://akash-dubey-portfolio-websites-herokuapp.com',
  location: 'Lucknow ,Up',
  email: null,
  hireable: null,
  bio: 'CSE-22',
  twitter_username: 'akashdubey2211',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};
